apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-task-manager-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-task-manager
  template:
    metadata:
      labels:
        app: student-task-manager
    spec:
      containers:
      - name: student-task-manager
        image: student-task-manager:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://host.minikube.internal:5432/student_task_manager
        - name: SPRING_DATASOURCE_USERNAME
          value: postgres
        - name: SPRING_DATASOURCE_PASSWORD
          value: password